version: '3.1'
services:
  db:
    image: mysql
    container_name: mysqlvenda
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3307:3306"
    volumes:
    - venda_volume:/var/lib/mysql

volumes:
  venda_volume: