server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/venda?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#      Esse comando faz com que o Hibernate printe os comandos SQL
#    show-sql: true

#      Esse comando faz com que o Spring printe os comandos SQL, que tem mais performance
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG